pruners:
  pruner_1:
    class: WoodburryFisherPruner
    epochs: [0,2,22]
    weight_only: True
    initial_sparsity: 0.0
    target_sparsity: 0.9
    modules: [ 
        features.0,
        features.3,
        features.7,
        features.10,
        features.14,
        features.17,
        features.20,
        features.24,
        features.27,
        features.30,
        features.34,
        features.37,
        features.40,
        #classifier 
        ]
    keep_pruned: False

trainers:
  default_trainer:
    optimizer:
      class: SGD
      #lr: 0.1
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0001


    lr_scheduler:
      class: ExponentialLR
      gamma: 0.1
      #epochs: [100,50,200] # 200 in total
      #epochs: [80,50,250] # 250 in total
      #epochs: [100,50,300] # 300 in total
      #epochs: [50,50,200] # 300 in total
      epochs: [50,100,300] # 300 in total
